version: '2'
services:
  ldap:
    image: lmccay/knox_sso_testing:knox
    container_name: kst_ldap
    command: /ldap.sh
    ports:
    #- "127.0.0.1:389:33389"
    - "172.17.0.1:389:33389"

  superset:
    build:
      context: superset
      args:
        SUPERSET_VERSION: 0.28.0
    # image: knoxsupersettesting_superset
    container_name: kst_superset
    ports:
    - 172.17.0.1:8088:8088
    command: /launcher.sh
    volumes:
     - ./logs:/var/log
     - ./keystores:/etc/ssl/keystores
    depends_on:
    - ldap

  knox:
    build:
      context: knox
      args:
        KNOX_VERSION: 1.2.0
    # image: lmccay/knox_sso_testing:knox
    container_name: kst_knox
    ports:
    - 8443:8443
    command: /gateway.sh
    # command: tail -f /dev/null
    volumes:
     - ./topologies:/knox/conf/topologies
     - ./logs:/knox/logs
     - ./applications:/knox/data/applications
     # - ./security:/knox/data/security
     - ./keystores:/knox/data/security/keystores
     - ./services/superset:/knox/data/services/superset
     - ./services/dummy:/knox/data/services/dummy
    depends_on:
    - superset

networks:
  default:
    external:
      name: example.com
