#!/bin/bash

set -euxo pipefail

# set -e

# Create an admin user - not necessary with LDAP
fabmanager create-admin --app superset $@

# Initialize the database
superset db upgrade

# Create default roles and permissions
superset init
